name = "AlgorithmsInterface"
uuid = "d1e3940c-cd12-4505-8585-b0a4b322527d"
authors = ["Ronny Bergmann <git@ronnybergmann.net>"]
version = "0.1.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"

[compat]
Dates = "1.10"
julia = "1.10"
